light:
- platform: artnet_led
  host: 192.168.1.239                              # IP of Art-Net Node
  port: 6038
  max_fps: 25                           # Max 40 per second
  refresh_every: 2                      # Resend values if no fades are running every x seconds, 0 disables automatic refresh
  node_type: artnet-controller                 # Which protocol to use
  universes:                            # Support for multiple universes
    1:                                  # Nr of Universe (see configuration of your Art-Net Node)
      send_partial_universe: false       # Only send the universe which contains data
      output_correction: quadratic      # optional: output correction for the whole universe, will be used as default if nothing is set for the channel
      devices:
        # Dimmer
        - channel: 1
          name: color_temp_light
          type: color_temp
          min_temp: 2000K
          max_temp: 6500K
          channel_setup:
            - d
            - t
            - 0
            - 0
            - 0
        - channel: 6
          name: rgbw_light
          type: rgbw

logger:
  default: info
  logs:
    custom_components.artnet_led: info
    pyartnet: debug

scene:
  - name: Romantic
    icon: "mdi:flower-tulip"
    entities:
      light.test_light:
        state: "on"
        brightness: 200
        transition: 10
  - name: Movies
    entities:
      light.test_light:
        state: "on"
        brightness: 0
        transition: 10

debugpy:


homeassistant:
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 0.0.0.0/0
      allow_bypass_login: true


# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
#tts:
#  - platform: google_translate

#automation: !include automations.yaml
#script: !include scripts.yaml
#scene: !include scenes.yaml
